# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9257fd7a43c0a3c4ab07f3c16dce1d2969ca0a22aec9e35482a3ad2b92b144ef9ebab7030bc1dc97cdfadb916f117163bc58a6440ae1d5987a97ceb6861db1d8

test:
  secret_key_base: 2450fbc9a81423c201bddc1bd2a282aff8f3713c74886c3cd4f7df5558b2e7d1cc20b6ce75970ed69004c7cc5d6a012fe45b7aa3205df38b14db5c5f4db641b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
